In [1]:
import pandas as pd

In [3]:
metar=pd.read_csv( r"C:\Users\GFD LAB\Documents\Anwesha Chakraborty\data\visibility, wind speed, rh, temp\VIDP (1).csv", skiprows=5)

In [4]:
metar["valid"] = pd.to_datetime(
    metar["valid"],
    dayfirst=False
)

In [5]:
metar = metar[metar["valid"].dt.minute == 0]

In [6]:
metar = metar[["valid", "vsby", "relh", "tmpc", "sped"]]

In [7]:
metar.rename(columns={
    "valid": "Datetime",
    "vsby": "Visibility",
    "relh": "RH",
    "tmpc": "Temperature",
    "sped": "WindSpeed"
}, inplace=True)

In [8]:
metar["Visibility"] = metar["Visibility"] * 1609.344

In [9]:
metar["WindSpeed"] = metar["WindSpeed"] * 0.44704

In [10]:
metar = metar.sort_values("Datetime").reset_index(drop=True)

In [11]:
metar.to_csv(r"C:\Users\GFD LAB\Documents\Anwesha Chakraborty\output\metar.csv",index=False)

In [13]:
metar.shape

(21689, 5)

In [14]:
print(metar.columns)

Index(['Datetime', 'Visibility', 'RH', 'Temperature', 'WindSpeed'], dtype='str')

In [15]:
metar.head()

             Datetime  Visibility     RH  Temperature  WindSpeed
0 2024-01-01 00:00:00    1207.008  87.56         12.0   2.056384
1 2024-01-01 01:00:00    1207.008  87.47         11.0   0.000000
2 2024-01-01 02:00:00    1207.008  87.47         11.0   2.056384
3 2024-01-01 03:00:00    1207.008  87.47         11.0   1.542288
4 2024-01-01 04:00:00    1207.008  87.47         11.0   1.542288

In [16]:
metar.tail()

                 Datetime  Visibility     RH  Temperature  WindSpeed
21684 2026-06-29 19:00:00  4506.16320  49.74         34.0   2.056384
21685 2026-06-29 20:00:00  4506.16320  49.74         34.0   2.056384
21686 2026-06-29 21:00:00  4007.26656  49.74         34.0   3.084576
21687 2026-06-29 22:00:00  4007.26656  49.74         34.0   3.084576
21688 2026-06-29 23:00:00  4007.26656  52.85         34.0   2.570480